name: front-build

on:
  push:
    branches:
      - feat/cicd

jobs:
  build:
    name: react build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout Github Action
        uses: actions/checkout@v4.1.1

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: 'yarn'

      - name: install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: react build
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-northeast-2

      - name: Upload /dist to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME}}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 dist s3://$BUCKET_NAME
